name: Publish binaries on Release
on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin, freebsd, openbsd]
        goarch: ["386", amd64, arm64, arm]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "arm"
            goos: darwin
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@master
      env:
        CGO_ENABLED: 0 # support alpine
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.20.3
        ldflags: "-s -w -X main.version=${{ github.event.release.tag_name }} -X main.commit=${{ github.sha }}"
        build_flags: -v

